from .Address import Address
from .Claim import Claim
from .Contact import Contact
from .Credential import Credential
from .CredentialType import CredentialType
from .Name import Name
from .Person import Person
from .Schema import Schema
from .Subject import Subject
