# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 17:03
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('DID', models.TextField(blank=True, max_length=60, unique=True)),
                ('verkey', models.BinaryField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DoingBusinessAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('dbaName', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DOING_BUSINESS_AS',
            },
        ),
        migrations.CreateModel(
            name='InactiveClaimReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('shortReason', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('displayOrder', models.IntegerField()),
            ],
            options={
                'db_table': 'INACTIVE_CLAIM_REASON',
            },
        ),
        migrations.CreateModel(
            name='IssuerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('issuerOrgTLA', models.CharField(max_length=255)),
                ('issuerOrgURL', models.CharField(blank=True, max_length=255, null=True)),
                ('DID', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ISSUER_SERVICE',
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('abbrv', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=1000)),
                ('displayOrder', models.IntegerField()),
                ('isOnCommonList', models.BooleanField()),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'JURISDICTION',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('addressee', models.CharField(blank=True, max_length=255, null=True)),
                ('addlDeliveryInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('unitNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('municipality', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('latLong', models.CharField(blank=True, max_length=255, null=True)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('doingBusinessAsId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api_v2.DoingBusinessAs')),
            ],
            options={
                'db_table': 'LOCATION',
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('locType', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('displayOrder', models.IntegerField()),
            ],
            options={
                'db_table': 'LOCATION_TYPE',
            },
        ),
        migrations.CreateModel(
            name='VerifiableClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('claimJSON', models.TextField(blank=True, null=True)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VERIFIABLE_CLAIM',
            },
        ),
        migrations.CreateModel(
            name='VerifiableClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('claimType', models.CharField(max_length=255)),
                ('base64Logo', models.CharField(blank=True, max_length=255, null=True)),
                ('issuerURL', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('schemaName', models.CharField(blank=True, max_length=255, null=True)),
                ('schemaVersion', models.CharField(blank=True, max_length=255, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('issuerServiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuerServices', to='api_v2.IssuerService')),
            ],
            options={
                'db_table': 'VERIFIABLE_CLAIM_TYPE',
            },
        ),
        migrations.CreateModel(
            name='VerifiableOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('orgId', models.CharField(max_length=255)),
                ('legalName', models.CharField(max_length=255)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('jurisdictionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifiableOrgJurisdictions', to='api_v2.Jurisdiction')),
            ],
            options={
                'db_table': 'VERIFIABLE_ORG',
            },
        ),
        migrations.CreateModel(
            name='VerifiableOrgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('orgType', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('effectiveDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('displayOrder', models.IntegerField()),
            ],
            options={
                'db_table': 'VERIFIABLE_ORG_TYPE',
            },
        ),
        migrations.AddField(
            model_name='verifiableorg',
            name='orgTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verifiableOrgTypes', to='api_v2.VerifiableOrgType'),
        ),
        migrations.AddField(
            model_name='verifiableclaim',
            name='claimType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimTypes', to='api_v2.VerifiableClaimType'),
        ),
        migrations.AddField(
            model_name='verifiableclaim',
            name='inactiveClaimReasonId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inactiveClaimReasons', to='api_v2.InactiveClaimReason'),
        ),
        migrations.AddField(
            model_name='verifiableclaim',
            name='verifiableOrgId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api_v2.VerifiableOrg'),
        ),
        migrations.AddField(
            model_name='location',
            name='locationTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locationTypes', to='api_v2.LocationType'),
        ),
        migrations.AddField(
            model_name='location',
            name='verifiableOrgId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api_v2.VerifiableOrg'),
        ),
        migrations.AddField(
            model_name='issuerservice',
            name='jurisdictionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuerServiceJurisdictions', to='api_v2.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='doingbusinessas',
            name='verifiableOrgId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doingBusinessAs', to='api_v2.VerifiableOrg'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('addressee', models.TextField(null=True)),
                ('civic_address', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('province', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'claim',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('wallet_id', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credential',
            },
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('processor_config', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credential_type',
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('did', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('abbreviation', models.TextField()),
                ('email', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'issuer',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='api_v2.Credential')),
            ],
            options={
                'db_table': 'name',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.TextField(null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='api_v2.Credential')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('origin_did', models.TextField()),
            ],
            options={
                'db_table': 'schema',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('source_id', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together=set([('name', 'version', 'origin_did')]),
        ),
        migrations.AddField(
            model_name='credentialtype',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_types', to='api_v2.Issuer'),
        ),
        migrations.AddField(
            model_name='credentialtype',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_types', to='api_v2.Schema'),
        ),
        migrations.AddField(
            model_name='credential',
            name='credential_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api_v2.CredentialType'),
        ),
        migrations.AddField(
            model_name='credential',
            name='topics',
            field=models.ManyToManyField(related_name='credentials', to='api_v2.Topic'),
        ),
        migrations.AddField(
            model_name='contact',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api_v2.Credential'),
        ),
        migrations.AddField(
            model_name='claim',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api_v2.Credential'),
        ),
        migrations.AddField(
            model_name='address',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='api_v2.Credential'),
        ),
        migrations.AlterUniqueTogether(
            name='credentialtype',
            unique_together=set([('schema', 'issuer')]),
        ),
    ]
