#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e
SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF

  Allows you to manage certain aspects of TheOrgBook environment.

  Usage: 
    $0 [options] [commands]

  Example:
    $0 -P -e test resetDatabase
    - This will reset the database in TheOrgBook's TEST environment.

  Commands:
  ========
    resetDatabase
      - Drop and recreate the database.
      - Rebuild search indexes.

    deleteDatabase
      - Deletes all databases off a pod and recycles the pod leaving it in a clean state.
      - Useful when database credentials change.

    hardReset
      - Delete the persistent indy wallet information.
      - Drop and recreate the database.
      - Rebuild search indexes.
      - Register the environment's DID with the ledger.

    resetSearchIndex
      - Delete and recreate the search index for a given environment.

    resetSolrCore
      - Delete and recreate the solr core for a given environment.

    rebuildSearchIndex
      - Rebuild the search index for a given environment.

    updateSearchIndex
      - Update the search index for a given environment.
      - Supports passing arguments to updateSearchIndex.sh.  For example:
          $0 -p bc-tob -e prod updateSearchIndex -b 500 -s 2019-07-04T00:00:00

    indexSynced
      - Check to see if the Solr indexes are syned with the database credentials.

    deleteTopic <topic_id>
      - delete the specified topic from the OrgBook database
      - topic_id *must* be the first option specified, e.g. `$0 <topic_id> -e dev`

    scaleUp
      - Scale up one or more pods.
        For example;
          $0 -e dev scaleUp django

    scaleDown
      - Scale down one or more pods.
        For example;
          $0 -e dev scaleDown django

    recycle
      - Recycle one or more pods.
        For example;
          $0 -e dev recycle django

EOF
}

# -----------------------------------------------------------------------------------------------------------------
# Define hook scripts:
# - These must be defined before the main settings script 'settings.sh' is loaded.
# -----------------------------------------------------------------------------------------------------------------
onRequiredOptionsExist() {
  (
if [ -z "${DEPLOYMENT_ENV_NAME}" ]; then
  _red='\033[0;31m'
  _nc='\033[0m' # No Color
      echo -e "\n${_red}You MUST specify an environment name using the '-e' flag.${_nc}"
      echo -e "${_red}Assuming a default would have unwanted consequences.${_nc}\n"
      return 1
    else
      return 0
fi
  )
}

onUsesCommandLineArguments() {
  (
    # This script is expecting command line arguments to be passed ...
    return 0
  )
}

# -----------------------------------------------------------------------------------------------------------------
# Initialization:
# -----------------------------------------------------------------------------------------------------------------
# Load the project settings and functions ...
_includeFile="ocFunctions.inc"
_settingsFile="settings.sh"
if [ ! -z $(type -p ${_includeFile}) ]; then
  _includeFilePath=$(type -p ${_includeFile})
  export OCTOOLSBIN=$(dirname ${_includeFilePath})

  if [ -f ${OCTOOLSBIN}/${_settingsFile} ]; then
    . ${OCTOOLSBIN}/${_settingsFile}
  fi

  if [ -f ${OCTOOLSBIN}/${_includeFile} ]; then
    . ${OCTOOLSBIN}/${_includeFile}
  fi
else
  _red='\033[0;31m'
  _yellow='\033[1;33m'
  _nc='\033[0m' # No Color
  echo -e \\n"${_red}${_includeFile} could not be found on the path.${_nc}"
  echo -e "${_yellow}Please ensure the openshift-developer-tools are installed on and registered on your path.${_nc}"
  echo -e "${_yellow}https://github.com/BCDevOps/openshift-developer-tools${_nc}"
fi

# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
resetDatabase() {
  _apiPodName=${1}
  _dbPodName=${2}
  if [ -z "${_apiPodName}" ] || [ -z "${_dbPodName}" ]; then
    echo -e \\n"resetDatabase; Missing parameter!"\\n
    exit 1
  fi

  switchProject
  exitOnError

  dropAndRecreateDatabaseWithMigrations ${_apiPodName} ${_dbPodName}
  rebuildSearchIndex ${_apiPodName}

  echoWarning "\nThe project's database has been reset."
  echoWarning "Use the GreenLight manage script to recycle the GreenLight pods."  
}

deleteDatabase() {
  _dbPodName=${1}
  if [ -z "${_dbPodName}" ]; then
    echo -e \\n"resetDatabase; Missing parameter!"\\n
    exit 1
  fi

  printAndAskToContinue "If you contiune all of the databases on ${_dbPodName} will be deleted.  All data will be lost."

  switchProject
  exitOnError

  deleteAndRecreateDatabase ${_dbPodName}

  echoWarning "\nThe databases on ${_dbPodName} have been deleted."
}

hardReset() {
  _apiPodName=${1}
  _dbPodName=${2}
  _walletDbPodName=${3}
  if [ -z "${_apiPodName}" ] || [ -z "${_dbPodName}" ] || [ -z "${_walletDbPodName}" ]; then
    echo -e \\n"resetDatabase; Missing parameter!"\\n
    exit 1
  fi

  printAndWait "If you are using GreenLight, use the GreenLight manage script to reset the GreenLight pods.\nWait for all of the pods to completely shut down before continuing."

  switchProject
  exitOnError

  # Scale down the API pod ...
  scaleDown ${_apiPodName}
  exitOnError
  printAndWait "Wait for the ${_apiPodName} pod to completely shut down before continuing."

  # Drop and recreate the application database ...
  dropAndRecreatePostgreSqlDatabase ${_dbPodName}
  exitOnError

  # Drop the wallet databases ...
  if podExists ${_walletDbPodName}; then
    deleteAndRecreateDatabase ${_walletDbPodName}
    exitOnError
  fi

  # Bring the API pod back up ...
  printAndWait "If you are resetting the ledger, wait for the ledger to completely start up before continuing."
  scaleUp ${_apiPodName}
  exitOnError
  printAndWait "Wait for the ${_apiPodName} pod to completely start up before continuing."

  rebuildSearchIndex ${_apiPodName}

  echoWarning "\nThe project's database and indy wallets have been reset."  
  echoWarning "If you are using GreenLight, use the GreenLight manage script to scale the GreenLight pods up."  
}

resetSearchIndex() {
  _apiPodName=${1}
  _solrPodName=${2}
  if [ -z "${_apiPodName}" ] || [ -z "${_solrPodName}" ]; then
    echo -e \\n"resetSearchIndex; Missing parameter!"\\n
    exit 1
  fi

  deleteSearchIndex "${_solrPodName}"

  recyclePods "${_solrPodName}"
  printAndWait "Wait for the ${_solrPodName} pod to completely start up before continuing."

  rebuildSearchIndex "${_apiPodName}"
}

resetSolrCore() {
  _apiPodName=${1}
  _solrPodName=${2}
  if [ -z "${_apiPodName}" ] || [ -z "${_solrPodName}" ]; then
    echo -e \\n"resetSolrCore; Missing parameter!"\\n
    exit 1
  fi

  deleteSolrCore "${_solrPodName}"

  recyclePods "${_solrPodName}"
  printAndWait "Wait for the ${_solrPodName} pod to completely start up before continuing."

  rebuildSearchIndex "${_apiPodName}"
}

deleteSolrCore() {
  _solrPodName=${1}
  if [ -z "${_solrPodName}" ]; then
    echo -e \\n"deleteSolrCore; Missing parameter!"\\n
    exit 1
  fi

  printAndAskToContinue "If you contiune the Solr core on ${_solrPodName} will be deleted."
  deleteFromPod "${_solrPodName}" "/opt/solr/server/solr/mycores/the_org_book"
  exitOnError
}

deleteSearchIndex() {
  _solrPodName=${1}
  if [ -z "${_solrPodName}" ]; then
    echo -e \\n"deleteSearchIndex; Missing parameter!"\\n
    exit 1
  fi

  printAndAskToContinue "If you contiune the search index on ${_solrPodName} will be deleted."
  deleteFromPod "${_solrPodName}" "/opt/solr/server/solr/mycores/the_org_book/data/index"
  exitOnError
}

rebuildSearchIndex() {
  _apiPodName=${1}
  if [ -z "${_apiPodName}" ]; then
    echo -e \\n"rebuildSearchIndex; Missing parameter!"\\n
    exit 1
  fi
  echoWarning "\nRebuilding the search index ..."
  echoWarning "The command may start interactively in the pod.  Please answer 'y' to the question if you are prompted."
  runInContainerInteractively ${_apiPodName} './rebuildSearchIndex.sh'
  exitOnError
}

updateSearchIndex() {
  (
    local OPTIND
    local OPTARG
    unset local args
    while getopts s:b: FLAG; do
      case $FLAG in
        * ) args="${args} -${FLAG} ${OPTARG}"
          ;;
      esac
    done
    shift $((OPTIND-1))
    
    _apiPodName=${1:-django}
    if [ -z "${_apiPodName}" ]; then
      echo -e \\n"updateSearchIndex; Missing parameter!"\\n
      exit 1
    fi

    echoWarning "\nUpdating the search index ..."
    args="$(echo "${args}" | sed -e 's/^[[:space:]]*//')"
    runInContainer ${_apiPodName} "./updateSearchIndex.sh ${args}"
  )
}

indexSynced() {
  _apiPodName=${1}
  _dbPodName=${2}

  indexInfo=$(runInContainer "${_apiPodName}" \
    'curl -s http://solr:8983/solr/the_org_book/admin/luke?wt=json&show=index&numTerms=0')

  indexCount=$(echo ${indexInfo} | sed 's~\(.*"numDocs":\)\([[:digit:]]\+\).*~\2~')
  actualCount=$(runInContainer ${_dbPodName} \
    'psql -d ${POSTGRESQL_DATABASE} -t -c "select count(*) from credential;"')

  indexDiff=$(( ${actualCount} - ${indexCount} ))

  if (( ${indexCount} == ${actualCount} )); then
    synced="true"
  else
    synced="false - Difference: ${indexDiff}"
  fi 

  echo
  echo "Indexes Synced: ${synced}"
  echo "Indexed Credentials: ${indexCount}"
  echo "Actual Credentials: ${actualCount}"
}

deleteTopic() {
  _topic_id = ${1}
  _apiPodName=${2:-django}
  if [ -z "${_apiPodName}" ]; then
    echo -e \\n"deleteTopic; Missing parameter!"\\n
    exit 1
  fi
  echoWarning "\nDeleting topic from OrgBook database ..."
  runInContainerInteractively ${_apiPodName} './deleteTopic.sh'
  exitOnError
}

# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
_cmd=$(toLower ${1})
shift

case "${_cmd}" in
  resetdatabase)
    # Allow all of the other parameters to be overridden ...
    apiPodName=${1:-django}
    dbPodName=${2:-postgresql}
    resetDatabase "${apiPodName}" "${dbPodName}"
    ;;
  deletedatabase)
    dbPodName=${1}
    deleteDatabase "${dbPodName}"
    ;;
  hardreset)
    # Allow all of the other parameters to be overridden ...
    apiPodName=${1:-django}
    dbPodName=${2:-postgresql}
    walletDbPodName=${3:-wallet-db}
    hardReset "${apiPodName}" "${dbPodName}" "${walletDbPodName}"
    ;;
  resetsearchindex)
    apiPodName=${1:-django}
    solrPodName=${2:-solr}
    switchProject
    exitOnError
    resetSearchIndex "${apiPodName}" "${solrPodName}"
    ;;
  resetsolrcore)
    apiPodName=${1:-django}
    solrPodName=${2:-solr}
    switchProject
    exitOnError
    resetSolrCore "${apiPodName}" "${solrPodName}"
    ;;
  rebuildsearchindex)
    apiPodName=${1:-django}
    switchProject
    exitOnError
    rebuildSearchIndex "${apiPodName}"
    ;;
  updatesearchindex)
    # apiPodName=${1:-django}
    updateSearchIndex ${@}
    ;;
  indexsynced)
    apiPodName=${1:-django}
    dbPodName=${2:-postgresql}
    indexSynced "${apiPodName}" "${dbPodName}"
    ;;
  deleteTopic)
    topic_id=${1}
    apiPodName=${2:-django}
    switchProject
    exitOnError
    deleteTopic "${topic_id}" "${apiPodName}"
    ;;
  scaleup)
    apiPodName=${1:-django}
    scaleUp ${@}
    ;;
  scaledown)
    scaleDown ${@}
    ;;
  recycle)
    recyclePods ${@}
    ;;
  *)
    echoWarning "Unrecognized command; ${_cmd}"
    usage
    ;;
esac

popd >/dev/null