# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('wallet_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('item_value', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='walletitem',
            unique_together=set([('wallet_name', 'item_type', 'item_id')]),
        ),
    ]
