# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletitem',
            name='item_value',
            field=models.TextField(blank=True),
        ),
    ]
