// Edit your app's name below
def APP_NAME = 'angular-on-nginx'

// Edit your environment TAG names below
def TAG_NAMES = ['dev', 'test', 'prod']

// You shouldn't have to edit these if you're following the conventions
def NGINX_BUILD_CONFIG = 'nginx-runtime'
def BUILD_CONFIG = APP_NAME + '-build'
def IMAGESTREAM_NAME = APP_NAME
def CONTEXT_DIRECTORY = 'tob-web'

@NonCPS
boolean triggerBuild(String contextDirectory) {
  // Determine if code has changed within the source context directory.
  def changeLogSets = currentBuild.changeSets
  def filesChangeCnt = 0
  for (int i = 0; i < changeLogSets.size(); i++) {
    def entries = changeLogSets[i].items
    for (int j = 0; j < entries.length; j++) {
      def entry = entries[j]
      //echo "${entry.commitId} by ${entry.author} on ${new Date(entry.timestamp)}: ${entry.msg}"
      def files = new ArrayList(entry.affectedFiles)
      for (int k = 0; k < files.size(); k++) {
        def file = files[k]
        def filePath = file.path
        //echo ">> ${file.path}"
        if (filePath.contains(contextDirectory)) {
          filesChangeCnt = 1
          k = files.size()
          j = entries.length
        }
      }
    }
  }
  
  if ( filesChangeCnt < 1 ) {
    echo('The changes do not require a build.')
    return false
  }
  else {
    echo('The changes require a build.')
    return true
  } 
}

node {
  if( triggerBuild(CONTEXT_DIRECTORY) ) {
    stage('build nginx runtime') {
      echo "Building: " + NGINX_BUILD_CONFIG
      openshiftBuild bldCfg: NGINX_BUILD_CONFIG, showBuildLogs: 'true'
      openshiftTag destStream: NGINX_BUILD_CONFIG, verbose: 'true', destTag: '$BUILD_ID', srcStream: NGINX_BUILD_CONFIG, srcTag: 'latest'
    }
    
    stage('build ' + BUILD_CONFIG) {
      echo "Building: " + BUILD_CONFIG
      openshiftBuild bldCfg: BUILD_CONFIG, showBuildLogs: 'true'
      openshiftTag destStream: IMAGESTREAM_NAME, verbose: 'true', destTag: '$BUILD_ID', srcStream: IMAGESTREAM_NAME, srcTag: 'latest'
    }
    
    stage('deploy-' + TAG_NAMES[0]) {
      openshiftTag destStream: IMAGESTREAM_NAME, verbose: 'true', destTag: TAG_NAMES[0], srcStream: IMAGESTREAM_NAME, srcTag: '$BUILD_ID'
    }
  }
  else {
    stage('No Changes') {
      currentBuild.result = 'SUCCESS'
    }
  }
}

// node {
  // stage('deploy-' + TAG_NAMES[1]) {
    // input "Deploy to " + TAG_NAMES[1] + "?"
    // openshiftTag destStream: IMAGESTREAM_NAME, verbose: 'true', destTag: TAG_NAMES[1], srcStream: IMAGESTREAM_NAME, srcTag: '$BUILD_ID'
  // }
// }

// node {
  // stage('deploy-'  + TAG_NAMES[2]) {
    // input "Deploy to " + TAG_NAMES[2] + "?"
    // openshiftTag destStream: IMAGESTREAM_NAME, verbose: 'true', destTag: TAG_NAMES[2], srcStream: IMAGESTREAM_NAME, srcTag: '$BUILD_ID'
  // }
// }
